### ISSUE TITLE
No output at all

### ISSUE THREAD

**Issue by vitich** [mxmCherry/taxes#6]
Hi! 
Installed version 2, changed the config file - no output.
With your test config from readme - there is also no output.
What am I doing wrong?
$ go version
go version go1.17.6 linux/amd64

**Comment by vitich** [comment]
I found an error.
It should be
```
business:
  base_currency: UAH
  tax_rate: 0.05
  rounding_precision: 2
transactions:
  - time: 2021-01-01T09:45:53Z
    amount: 100.12
    currency: USD

```
Please fix in Readme
